// ===== MENU PAGE =====

let currentCategory = 'all';

function renderMenuPage(container) {
  const reservationData = JSON.parse(sessionStorage.getItem('pendingReservation') || 'null');
  
  if (!reservationData) {
    showToast('Data reservasi tidak ditemukan', 'error');
    Router.navigate('/reservation');
    return;
  }
  
  container.innerHTML = `
    <main class="max-w-6xl mx-auto px-4 py-8 pb-32">
      <h1 class="font-display text-3xl text-forest mb-2">Pilih Menu</h1>
      <p class="text-gray-600 mb-6">Pre-order menu Anda (opsional)</p>

      <!-- Reservation Summary -->
      <div class="bg-forest/5 border border-forest/20 rounded-2xl p-4 mb-6">
        <div class="flex items-center gap-3">
          <i data-lucide="calendar-check" class="w-5 h-5 text-forest"></i>
          <div class="flex-1 text-sm">
            <p class="font-semibold text-forest">
              Meja ${reservationData.tableNumber} • ${reservationData.guestCount} orang
            </p>
            <p class="text-gray-600">
              ${formatDate(reservationData.date)} • ${reservationData.time} - ${reservationData.endTime}
            </p>
          </div>
          <a href="#/reservation" class="text-forest text-sm font-medium hover:underline">
            Ubah
          </a>
        </div>
      </div>

      <!-- Categories -->
      <div class="flex gap-2 mb-6 overflow-x-auto pb-2">
        <button onclick="filterMenu('all', this)" class="cat-btn ${currentCategory === 'all' ? 'active-cat' : ''}">
          Semua
        </button>
        <button onclick="filterMenu('Food', this)" class="cat-btn ${currentCategory === 'Food' ? 'active-cat' : ''}">
          Food
        </button>
        <button onclick="filterMenu('Snack', this)" class="cat-btn ${currentCategory === 'Snack' ? 'active-cat' : ''}">
          Snack
        </button>
        <button onclick="filterMenu('Beverage', this)" class="cat-btn ${currentCategory === 'Beverage' ? 'active-cat' : ''}">
          Beverage
        </button>
      </div>

      <!-- Menu Grid -->
      <div id="menuGrid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <!-- Will be generated by JS -->
      </div>
      
      <!-- Skip Button -->
      <div class="mt-8 text-center">
        <button onclick="skipMenu()" class="text-forest font-medium hover:underline">
          Lewati, lanjut ke pembayaran →
        </button>
      </div>
    </main>

    <!-- Sticky Cart Summary -->
    <div id="cartSummary" class="cart-summary">
      <div class="max-w-6xl mx-auto flex items-center justify-between gap-4">
        <div>
          <p class="text-sm text-gray-600">Total Pesanan</p>
          <p class="text-xl font-bold text-forest" id="cartTotal">Rp 0</p>
        </div>
        <button onclick="proceedToPayment()" class="btn btn-primary">
          Lanjut ke Pembayaran →
        </button>
      </div>
    </div>
  `;
  
  renderMenu();
}

function renderMenu() {
  const grid = document.getElementById('menuGrid');
  if (!grid) return;
  
  // ✅ PERBAIKAN: Gunakan menuItems global dari products.js
  // menuItems sudah tersedia karena products.js di-load di index.html
  if (typeof menuItems === 'undefined') {
    grid.innerHTML = `
      <div class="col-span-full text-center py-12 text-red-500">
        <i data-lucide="alert-circle" class="w-12 h-12 mx-auto mb-2"></i>
        <p>Data produk tidak ditemukan</p>
      </div>
    `;
    if (window.lucide) lucide.createIcons();
    return;
  }
  
  const filtered = currentCategory === 'all' 
    ? menuItems 
    : menuItems.filter(item => item.cat === currentCategory);
  
  const menuCart = JSON.parse(sessionStorage.getItem('menuCart') || '[]');
  
  if (filtered.length === 0) {
    grid.innerHTML = `
      <div class="col-span-full text-center py-12 text-gray-400">
        <i data-lucide="package" class="w-12 h-12 mx-auto mb-2 opacity-30"></i>
        <p>Belum ada menu di kategori ini</p>
      </div>
    `;
    if (window.lucide) lucide.createIcons();
    return;
  }
  
  grid.innerHTML = filtered.map(item => {
    const cartItem = menuCart.find(c => c.id === item.id);
    const qty = cartItem ? cartItem.qty : 0;
    
    // ✅ PERBAIKAN: Handle path gambar dengan helper
    const imagePath = resolveImagePath(item.images);
    
    return `
      <div class="menu-card stagger-item">
        <div class="menu-card-image">
          <img src="${imagePath}" alt="${item.name}" 
               onerror="this.onerror=null; this.src='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22%3E%3Crect fill=%22%23EFE7DE%22 width=%22100%22 height=%22100%22/%3E%3Ctext x=%2250%22 y=%2255%22 text-anchor=%22middle%22 font-size=%2240%22%3E🍽️%3C/text%3E%3C/svg%3E'">
        </div>
        <div class="menu-card-body">
          <h3 class="menu-card-title">${item.name}</h3>
          <p class="menu-card-category">${item.cat}</p>
          <p class="menu-card-description">${item.details || ''}</p>
          <div class="menu-card-footer">
            <span class="menu-card-price">${formatCurrency(item.price)}</span>
            ${qty > 0 ? `
              <div class="qty-control">
                <button onclick="updateCartQty(${item.id}, -1)" class="qty-btn">−</button>
                <span class="qty-value">${qty}</span>
                <button onclick="updateCartQty(${item.id}, 1)" class="qty-btn">+</button>
              </div>
            ` : `
              <button onclick="addToCart(${item.id})" class="btn btn-primary" style="padding: 0.5rem 1rem; font-size: 0.875rem;">
                + Tambah
              </button>
            `}
          </div>
        </div>
      </div>
    `;
  }).join('');
  
  if (window.lucide) lucide.createIcons();
  updateCartSummary();
}

/**
 * ✅ Helper: Resolve path gambar agar bekerja di berbagai lokasi
 */
function resolveImagePath(path) {
  if (!path) return '';
  
  // Jika sudah absolut (dimulai dengan / atau http)
  if (path.startsWith('/') || path.startsWith('http')) {
    return path;
  }
  
  // Jika relative, asumsikan dari root assets
  // Hapus prefix ../ jika ada
  const cleanPath = path.replace(/^(\.\.\/)+/, '');
  return '/' + cleanPath;
}

function filterMenu(category, btn) {
  currentCategory = category;
  
  // Update active button
  document.querySelectorAll('.cat-btn').forEach(b => {
    b.classList.remove('active-cat');
  });
  if (btn) btn.classList.add('active-cat');
  
  renderMenu();
}

function addToCart(itemId) {
  let menuCart = JSON.parse(sessionStorage.getItem('menuCart') || '[]');
  
  // ✅ Gunakan menuItems global
  const item = menuItems.find(m => m.id === itemId);
  if (!item) return;
  
  const existing = menuCart.find(c => c.id === itemId);
  if (existing) {
    existing.qty++;
  } else {
    menuCart.push({
      id: item.id,
      name: item.name,
      price: item.price,
      image: item.images,
      qty: 1
    });
  }
  
  sessionStorage.setItem('menuCart', JSON.stringify(menuCart));
  renderMenu();
}

function updateCartQty(itemId, delta) {
  let menuCart = JSON.parse(sessionStorage.getItem('menuCart') || '[]');
  
  const item = menuCart.find(c => c.id === itemId);
  if (!item) return;
  
  item.qty += delta;
  if (item.qty <= 0) {
    menuCart = menuCart.filter(c => c.id !== itemId);
  }
  
  sessionStorage.setItem('menuCart', JSON.stringify(menuCart));
  renderMenu();
}

function updateCartSummary() {
  const menuCart = JSON.parse(sessionStorage.getItem('menuCart') || '[]');
  const summary = document.getElementById('cartSummary');
  const totalEl = document.getElementById('cartTotal');
  
  if (!summary || !totalEl) return;
  
  if (menuCart.length === 0) {
    summary.classList.remove('visible');
    return;
  }
  
  const total = menuCart.reduce((sum, item) => sum + (item.price * item.qty), 0);
  totalEl.textContent = formatCurrency(total);
  summary.classList.add('visible');
}

function skipMenu() {
  sessionStorage.setItem('menuCart', JSON.stringify([]));
  Router.navigate('/payment');
}

function proceedToPayment() {
  const menuCart = JSON.parse(sessionStorage.getItem('menuCart') || '[]');
  if (menuCart.length === 0) {
    showToast('Silakan pilih minimal 1 menu atau lewati', 'warning');
    return;
  }
  Router.navigate('/payment');
}